@startuml

actor DA as "Data Analyst"

rectangle Database

rectangle DS as "DB System" {

    usecase UC1 as "Print Languages from Most Speakers"
    usecase UC2 as "Print Population in Cities of Territory"
    usecase UC3 as "Print Population in Territory"
    usecase UC4 as "Print Most Populated Cities in Area"
    usecase UC5 as "Print Capital Cities Ordered from Largest Population"
    usecase UC6 as "Print Top Populated cities in Territory"
    usecase UC7 as "Print Cities ordered by most Populated"
    usecase UC8 as "Print Top Populated Countries in Territory"
    usecase UC9 as "Print Countries Populated From Largest"

    DA - UC1
    DA - UC2
    DA - UC3
    DA - UC4
    DA - UC5
    DA - UC6
    DA - UC7
    DA - UC8
    DA - UC9




    DS - Database

}

@enduml