@startuml

actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC4 as "GetAllCities"

    usecase UCa as "Print all Countries"

    HR - UC4
    UC4 ..> UCa : include
    UC4 - Database
}

@enduml